jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-version: ${{ matrix.java-version }}
    - continue-on-error: true
      name: Build with Maven
      run: mvn -B package --file pom.xml
    - continue-on-error: true
      name: Test with Maven
      run: mvn -B test --file pom.xml
    strategy:
      matrix:
        java-version:
        - 8
        - 11
        - 18
        - 22
name: Atmosphere
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
